name: CI Deploy (UAT)

on:
  pull_request:
    branches:
      - 'main'
      - 'uat-branch'

jobs:
  Deploy:
    uses: Salesforce-Github-actions/salesforce-devops/.github/workflows/delta-deploy.yml@main
    with:
      environment: UAT
      integrationBranch: uat-branch
      from: HEAD^1
      to: HEAD
      dryRun: false
    secrets: inherit
