name: CI Deploy (PRODUCTION)

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Deploy:
    uses: Salesforce-Github-actions/salesforce-devops/.github/workflows/delta-deploy.yml@main
    with:
      environment: PRODUCTION
      integrationBranch: main
      from: HEAD^1
      to: HEAD
      dryRun: false
    secrets: inherit
