name: CI Deploy (QA)

on:
  pull_request:
    branches:
      - 'qa-branch'
      - 'int-branch'

jobs:
  Deploy:
    uses: Salesforce-Github-actions/salesforce-devops/.github/workflows/delta-deploy.yml@main
    with:
      environment: QA
      integrationBranch: int-branch
      from: HEAD^1
      to: HEAD
      dryRun: false
    secrets: inherit
